name: FantasyBosses
version: 1.0
main: com.fantasybosses.FantasyBosses
description: Custom boss plugin featuring Goblin Boss and Xal Rath
author: Phillip
api-version: 1.20
depend: [NBTAPI]
commands:
  summongoblin:
    description: Summons the Goblin Boss
    usage: /<command>
    permission: goblinboss.summon
  summonxalrath:
    description: Summons Xal Rath, the Sovereign of the Abyss
    usage: /<command>
    permission: xalrath.summon
permissions:
  goblinboss.summon:
    description: Allows the player to summon the Goblin Boss
    default: op
  xalrath.summon:
    description: Allows the player to summon Xal Rath
    default: op
